---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wave-cfg
  labels:
    app: wave-cfg
data:
  config.yml: |
    wave:
      debug: true
      server:
        url: "http://localhost:9090/"
      tokens:
        cache:
          maxDuration: "12h"
      registries :
        default: cr.seqera.io
        docker.io:
          username: "${DOCKER_USER:}"
          password: "${DOCKER_PAT:}"
        cr.seqera.io:  
          username: 'robot$developers'
          password: 'qAElA1YJ4J7ktb9qt3ChpgMRJ5Cy9BJ0'
      build:
        timeout: "15m"
        workspace: "/efs/wave/build"
        repo: "cr.seqera.io/developers/wave"
        cache: "cr.seqera.io/developers/cache"
        k8s:
          storage:
            mountPath: "/efs/wave/build"
            claimName: "wave-build"
          namespace: "default"
          serviceAccount: "wave-sa"            
          nodeSelector:
            'linux/amd64': 'service=wave-build'
            'linux/arm64': 'service=wave-build-arm64'
    datasources:
      default:
        dialect: H2
        url: "jdbc:h2:mem:test_mem"
        driverClassName: "org.h2.Driver"
        username: "sq"
        password: ""
    #redis:
    #  uri: "redis://redis:6379"
    rate-limit:
      build:
        max: 100
        duration: 1h
      pull:
        max: 1000
        duration: 1h
    stats:
      surrealdb:        
        ur: http://surrealdb:8000
