---
towerreg:
  arch: x86_64
  registries:
    docker_io:
      host: https://registry-1.docker.io
      auth:
        username: "${DOCKER_USER}"
        password: "${DOCKER_PAT}"
        url: https://auth.docker.io/token
        service: registry.docker.io
    quay_io:
      host: https://quay.io
      auth:
        username: "${QUAY_USER}"
        password: "${QUAY_PAT}"
        url: https://quay.io/v2/auth
        service: quay.io
---
wave:
  arch: x86_64
  registries:
    - name: 'docker.io'
      username: "${DOCKER_USER}"
      password: "${DOCKER_PAT}"
    - name: 'quay.io'
      username : "${QUAY_USER}"
      password : "${QUAY_PAT}"
