---
wave:
  arch: "x86_64"
  registries:
    docker:
      username: "${DOCKER_USER}"
      password: "${DOCKER_PAT}"
    quay:
      username: "${QUAY_USER}"
      password: "${QUAY_PAT}"
    amazon:
      username : "${AWS_ACCESS_KEY_ID}"
      password : "${AWS_SECRET_ACCESS_KEY}"
    azurecr:
      username : "${AZURECR_USER}"
      password : "${AZURECR_PAT}"
    google:
      credentials : "${GOOGLE_SERVICE_CREDENTIALS}"
...
