---
towerreg:
  arch: x86_64
  registries:
    - name: docker.io
      host: registry-1.docker.io
      auth:
        username: "${DOCKER_USER}"
        password: "${DOCKER_PAT}"
        url: auth.docker.io/token
        service: registry.docker.io
    - name: quay.io
      host: quay.io
      auth:
        username: "${QUAY_USER}"
        password: "${QUAY_PAT}"
        url: quay.io/v2/auth
        service: quay.io
